name: "Test"
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      force:
        description: "Force running tests? (yes/no)"
        required: true
        default: yes

jobs:
  Conditionals:
    name: "Conditionals"
    runs-on: ubuntu-latest
    outputs:
      flag: ${{ env.flag }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: "Verify if any of the image-involved files changed"
        id: changed_files
        uses: tj-actions/changed-files@v11.5
        with:
          files: |
            classmapper/**
            tests/**
            .github/workflows/*.yaml
      - name: "Set output flag"
        if: ${{ steps.changed_files.outputs.any_changed == 'true' || github.event.inputs.force == 'yes' }}
        run: echo "flag=true" >> $GITHUB_ENV

  Test:
    name: "Test"
    runs-on: ubuntu-latest
    needs:
      - conditionals
    if: ${{ needs.Conditionals.outputs.flag == 'true' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: "Setup Python"
        uses: actions/setup-python@master
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: "Install requirements"
        run: pip install -r requirements-test.txt
      - name: "Test"
        run: pytest -sv .
